Ensure `free_energy` property is `float` (#225)
The `Calculator.results` dictionary from an M3GNet run yields something like `'free_energy': array(-4.0938973, dtype=float32)` for the free energy property. This causes some havoc with monty (traceback below) since the array isn't iterable. We should really make this a `float` instead anyway. That's what I do in this PR.

The monty issue, if you're curious:
```
File ~/software/miniconda/envs/mlp/lib/python3.11/site-packages/monty/json.py:678, in jsanitize(obj, strict, allow_bson, enum_values, recursive_msonable)
    673     return [
    674         jsanitize(i, strict=strict, allow_bson=allow_bson, enum_values=enum_values)
    675         for i in obj
    676     ]
    677 if np is not None and isinstance(obj, np.ndarray):
--> 678     return [
    679         jsanitize(i, strict=strict, allow_bson=allow_bson, enum_values=enum_values)
    680         for i in obj.tolist()
    681     ]
    682 if np is not None and isinstance(obj, np.generic):
    683     return obj.item()

TypeError: 'float' object is not iterable
```

Signed-off-by: Andrew S. Rosen <asrosen93@gmail.com>